### ISSUE TITLE
Module build failed: VariableDeclarator expected node to be of a type ["Expression"]

### ISSUE THREAD

**Issue by ingro** [gajus/babel-plugin-transform-export-default-name#1]
Hello! I was trying your plugin and babel started throwing errors liks this one:

```
Module build failed: TypeError: D:/projects/app/src/scripts/reducers/list.js: Property init of VariableDeclarator expected node to be of a type ["Expression"] but instead got "FunctionDeclaration"
```

The function in question is something like this:

```
export default function list(state = DEFAULT_STATE, action) {
    ...
}
```

Is this expected? I have to manually convert my exports to:

```
export default (state = DEFAULT_STATE, action) => {
    ...
}
```

**Comment by gajus** [comment]
Update to v1.0.4. I accidentally published broken release.

Please confirm if the issue persist.

**Comment by ingro** [comment]
Yup, no errors with 1.0.4, thanks for the fix!
