### ISSUE TITLE
HOC support

### ISSUE THREAD

**Issue by Guria** [gajus/babel-plugin-transform-export-default-name#13]
With Redux and Cerebral we often have components wrapped by hoc:
```js
export default connect(mapStateToProps, bindActionCreators)(({}) => <div />)
```

Can we support this case and name component defined by arrow function?

**Comment by gajus** [comment]
Whats the input and whats the expected output code?

**Comment by Guria** [comment]
Unfortunately libraries could have different syntax for HOC.
For instance, Redux use decorator like syntax, and Cerebral use last argument in connect call.

### redux
```js
// some-component.js
import React from 'react'
import {connect} from 'react-redux'

export default connect(mapStateToProps)((props) => <div />)
```
output
```js
// some-component.js
import React from 'react'
import {connect} from 'react-redux'

export default connect(mapStateToProps)(function SomeComponent(props) {return <div />})
```
### cerebral
```js
// some-component.js
import React from 'react'
import {connect} from 'cerebral/react'

export default connect(mapStateToProps, (props) => <div />)
```
output
```js
// some-component.js
import React from 'react'
import {connect} from 'react-redux'

export default connect(mapStateToProps, function SomeComponent(props) {return <div />})
```

**Comment by Guria** [comment]
Another difference related to React is that function should be capitalized

**Comment by gajus** [comment]
This is out of scope for this library. As you can see from your examples, this transformation requires making heavy assumptions about the codebase.

I wouldn't even bother creating this as a separate plugin. This is leaning towards overengineering for a very specific use case. Just my 2 cents.

Thank you for raising the suggestion.

**Comment by Guria** [comment]
Yeah. I see your point. And thought about specific plugin as well. Just wanted to put forward it here first.
Now at least you have a place where to point for future similar suggestions. :)
