### ISSUE TITLE
Decorators are not supported yet in 6.x pending proposal update.

### ISSUE THREAD

**Issue by gajus** [gajus/babel-plugin-transform-export-default-name#2]
This code:

``` js
import React from 'react';

export default class extends React.Component {
    render () {
        return <div>{this.props.children}</div>;
    }
};

```

Produces this error:

``` js
Module build failed: SyntaxError: ./src/app/components/ViewportComponent/index.js: Decorators are not supported yet in 6.x pending proposal update. (This is an error on an internal node. Probably an internal error. Location has been estimated.)
  1 | import React from 'react';
  2 |
  3 | export default class extends React.Component {
  4 |     render () {
  5 |         return <div>{this.props.children}</div>;
  6 |     }
  7 | };
  8 |
```

Removing `transform-export-default-name` from `.babelrc` makes it work.

**Comment by ghost** [comment]
I added a test case with the same code to confirm if it works or not and found that it's working fine.

**Comment by ghost** [comment]
I am closing this as test case is passing correctly. I have a feeling that this might not be related to our plugin. Are you sure it's with our plugin? Please share if there is stack trace that points to our code.

**Comment by gajus** [comment]
You are right. It was a case of bad plugin order. See https://phabricator.babeljs.io/T7079
