### ISSUE TITLE
Use folder name if the filename is `index.xxx`

### ISSUE THREAD

**Issue by andersekdahl** [gajus/babel-plugin-transform-export-default-name#3]
It's a common convention to have a file called `index.xxx` in a folder for the file that is the main module of that folder. And with sufficiently many of such files, this plugin becomes a bit less usable.

I was wondering what you think about checking if the file name without extension is `index` and in that case take the folder name instead?

**Comment by gajus** [comment]
> I was wondering what you think about checking if the file name without extension is index and in that case take the folder name instead?

It does that already.

**Comment by gajus** [comment]
Correction. It was supposed to do that already. I don't see this logic in the code base:

https://github.com/gajus/babel-plugin-transform-export-default-name/blob/319ed5b0d3c7088d7aa2242fe5ae3fc89314894c/src/index.js#L48-L60

I don't have time to do this change, but will accept a PR.
